title: "[Plant] Emot[ions]"
email: duerr.sebastian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploring happiness through plants with ML
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plantions.github.io" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
twitter_username: duerrseb
github_username:  seduerr91

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
